typesense/typesense-js

- src/Typesense/ApiCall.js
- src/Typesense/Documents.js
Adds a user-provided AbortController parameter to the search function so that in-flight searches whose results have become obsolete may be cancelled before completing. 
See https://developer.mozilla.org/en-US/docs/Web/API/AbortController for motivation.
> Add cancellability to search requests.

- .gitignore
- package-lock.json
- src/Typesense/ApiCall.ts
- src/Typesense/Documents.ts
- test/Typesense/Documents.spec.js
This pull request closes #87 
- `performRequest()` now accepts `responseType` as an optional parameter. That parameter is passed to Axios when making a request.
- `get()` now accepts `responseType` in it's optional parameters
- Added function called `exportStream`. It's functionally the same as `export()` the only difference is it now it passes `{ responseType: "stream" }` to the `this.apiCall.get()`.
[Axios doesn't support returning a stream in the browser](https://github.com/axios/axios/issues/479). So if this is called in the browser it'll just return a string like normal. Not sure if this needs to be documented or not. We could add a note to the JSDoc comment although I imagine most people wouldn't be using the export methods in the browser anyway since they require admin keys.
All …
> Create exportStream method

- src/Typesense/Documents.ts
This PR fixes this issue: https://github.com/typesense/typesense-js/issues/81. The reported issue was that the incoming document stream had too many objects while parsing via `JSON.stringify`. Since we don't run `stringify` on the complete documents object, but just the individual document, this means the user was trying to pass in an object with a very large number of keys.
In case this error pops up in the future, an error message will be displayed with the proper StackOverflow link.
> fix: display error message if document has too many keys

- src/Typesense/Documents.ts
Reverts typesense/typesense-js#88. 
More context here: https://github.com/typesense/typesense-js/pull/88#issuecomment-987524666
> Revert "fix: display error message if document has too many keys"

- src/Typesense/Collection.ts
Typesense v0.22.1 adds support for fields that are arrays of geopoints. However if you try to create a collection schema that includes a fields with the type `geopoint[]` you get a type error when using this library.
This PR adds the `geopoint[]` value to `FieldType` preventing devs from getting this inaccurate error.
> Adding Missing FieldType 'geopoint[]'

- src/Typesense/SearchOnlyDocuments.ts
There seem to be an issue when building a production build, specifically using Vite.
`Documents.RESOURCEPATH` returns undefined. Since this is a getter defined in `SearchOnlyDocuments` and `Documents` gets it by *inheritance*, I figured we could probably just remove the reference to Documents. 
I think the issue is caused by the circular dependency between `SearchOnlyDocuments` and `Documents` and gets a bit muffled at build/shrinking time, so this looks like a proper fix.
I can confirmed it resolved our issue on our side.
See associated [Slack thread](https://typesense-community.slack.com/archives/C01P749MET0/p1641500212020400)
> Remove SearchOnlyDocuments circular dependency

- src/Typesense/Health.ts
Changed the type of HealthResponse to accurately reflect the actual response received from the /health endpoint.
See: https://typesense.org/docs/0.22.2/api/cluster-operations.html#health
This PR changes `status: string` to `ok: boolean` in the `HealthResponse` interface.
Fixes following typescript error:
> Fix: change HealthResponse to correct typing

- src/Typesense/Operations.ts
Adds `cache/clear` option to the operation union type, to indicate it's existence.
This makes use of the existing operation endpoint here: https://github.com/typesense/typesense/blob/483ed4d533e8a657784472e3a3066298fa085c44/src/main/typesense_server.cpp#L77
It is, unfortunately, an undocumented flow. One that complements the usage of `useServerSideSearchCache` on the client side.
It would be really helpful to document that the use of the `useServerSideSearchCache`, or it's direct API dependant, `use_cache` ([link](https://typesense.org/docs/0.23.1/api/search.html#caching-parameters)), stores the result in memory, and can be cleared using the cache/clear operation when the immediate propagation of document update is needed.
> feat: add cache/clear to list of known operations

- src/Typesense/MultiSearch.ts
- generic type is carried by perform function and not the class
- type annotation is a tuple of Document schema, and the return type is a mapped tuple of SearchResponse of the specified documentSchema, in the same order
Usage would be : 
```typescript
type Employee = {name: string}
type Company = {orgName: string}
res = await client.multiSearch.perform<[Employee, Company]>(
[
{q, query_by: "name", collection: "employees"},
{q, query_by: "orgName", collection: "companies"}
]
)
[employees, companies] = res.results
```
> MultiSearch: multiSearch.perform types

- src/Typesense/Collection.ts
- src/Typesense/Documents.ts
- src/Typesense/SearchOnlyDocuments.ts
1. [Add `curated` param to `SearchResponseHit` type](https://github.com/typesense/typesense-js/commit/32377152dfa98b20c7fa091dd009c7ce3d2566c4)
2. [Improve `drop` field schema for `collection.update()`](https://github.com/typesense/typesense-js/commit/45b73de111bcc20f039e0fdd3133def56c9d2ccc)
- Prior implementation required "type" to be specified when dropping a field. Now only name, and `drop: true` are required/valid.
3. [Improved handling of searchParams](https://github.com/typesense/typesense-js/commit/4150173099685193522c5aa380c7c238d3c8da98)
- When specifying search params that are potentially comma separated, an array can now be passed which automatically joins the values with a comma into one string to then pass along to the search endpoint.
- See commit for more detail.
> Typescript adjustments + search param array handling

- src/Typesense/Errors/ImportError.ts
The docs indicate that the error thrown by `import()` (as in: `client.collections(...).documents().import(...)`) contains a key `importResults`. In my usage, I found that the runtime type of the value of `importResults` is an array, which seems to contain either `ImportResponseSuccess` or `ImportResponseFail`. At the moment I'm force-casting to override the type given by the library, but if my experimentation is correct, it'd be good to include the correct type here.
> Use ImportResponse[] as type of ImportError.importResults

- src/Typesense/Documents.ts
- Introduce the `drop_tokens_mode` parameter to the `SearchParams` interface, allowing more fine-grained control over token dropping behavior during search operations.
> feat(search_params): add drop_tokens_mode to search params interface

- src/Typesense/Documents.ts
- Enhance the `SearchParams` interface in `Documents.ts` by adding the `override_tags` option. This option allows specifying tags for overriding search behavior, providing greater flexibility in query customization.
> fix: add override tags params to search params interface

- src/Typesense/Key.ts
Add the `autodelete` parameter from the [API key](https://typesense.org/docs/27.1/api/api-keys.html#arguments) arguments to the API key interface.
> fix: add autodelete parameter to api key create schema

- src/Typesense/ApiCall.ts
- src/Typesense/Configuration.ts
Fixed the way numRetries is set during configuration.
WAS: if `falsy` then use fallback (i.e. use node config, or eventually default value of 3)
NOW: use fallback only if undefined
> fix: allow numRetries = 0

- src/Typesense/AnalyticsEvent.ts
The current implementation of the Analytics Event interface has two issues that could lead to runtime errors and type inconsistencies:
1. The `data` property is marked as optional (`?`), but according to Typesense's OpenAPI specification, it should be required.
2. The use of the `object` type for the `data` property is too permissive and doesn't provide proper type safety or property access guarantees.
These changes align our type definitions with the official Typesense API specification while providing better type safety and developer experience.
1. **In `src/Typesense/AnalyticsEvent.ts`**:
- Made `data` property required by removing the optional (`?`) modifier
- Changed `data` type from `object` to `Record<string, unknown>` to:
- Ensure only plain objects with string keys are accepted
- …
> fix(analytics): improve event type definition and enforce required data property

- lib/Typesense/Documents.d.ts
TypeScript was complaining about invalid config values when I was fooling around with the new "facet_strategy" parameter that was introduced in v27.0. It seems like this was the only missing parameter for faceting, phew! :)
> add missing facet_strategy option to SearchParams to catch up to v27

- src/Typesense/Documents.ts
Some changes must have removed `facet_strategy` from the `SearchParams` interface, as reported by #244. This adds `facet_strategy` back to the `SaerchParams` interface.
> Add facet strategy to search params interface

- src/Typesense/RequestWithCache.ts
Fixes a tsc error about `oldestEntry` potentially being undefined:
```ts
const isCacheOverMaxSize = this.responseCache.size > maxSize;
if (isCacheOverMaxSize) {
const oldestEntry = this.responseCache.keys().next().value; // ❌ Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
this.responseCache.delete(oldestEntry);
}
```
to just checking if it is defined, otherwise it just moves on:
```ts
const oldestEntry = this.responseCache.keys().next().value;
if (oldestEntry) {
this.responseCache.delete(oldestEntry);
}
```
This change tries to address the type error while not introducing any regressions by changing the underlying logic by throwing or returning early.
> Request cache: Fix type error when deleting possibly undefined oldest entry

- src/Typesense/Documents.ts
Since `text_match_info` returns `best_field_score` and `score` as numbers in string format, Typescript's template literals allow to assert that the underlying type is a number. This change provides enhancements to the overall typesafety of the client.
> fix(hit-res): use template literals to assert type of stringified nums

- src/Typesense/ApiCall.ts
This handles cases where the error code isn't returned by the error like here:
```shell
Request #1734010721681: Request to Node 0 failed due to "undefined Request failed with HTTP code 503"
```
> fix: handle undefined error codes in logger warnings

- src/Typesense/ApiCall.ts
This PR addresses a critical issue where Typesense library users encounter "Illegal invocation" errors when using custom Axios adapters in Cloudflare Workers environment. The error occurs because the fetch adapter loses its `this` context when used in Workers. This implementation ensures proper binding of the adapter to the correct context, making the library usable on edge computing environments.
1. **New Method in `ApiCall.ts`**:
- `getAdapter()`: A private method that intelligently handles Axios adapter configuration:
- Safely returns `undefined` when no adapter is configured
- Preserves function adapters as-is when directly provided
- Automatically detects Cloudflare Workers environment
- Binds the adapter to `globalThis` specifically in Workers environment
1. **In `ApiCall.ts`**:
- …
> Fix Axios adapter binding for Cloudflare Workers environment

- .github/workflows/tests.yml
Since  `actions/upload-artifact@v3` is getting deprecated, new workflow runs will be failing after Jan 30. This just bumps the version to the latest supported one.
> ci: bump actions/upload-artifact to v4

- src/Typesense/Client.ts
- src/Typesense/Collection.ts
- src/Typesense/Documents.ts
- src/Typesense/MultiSearch.ts
- src/Typesense/Operations.ts
- src/Typesense/Stemming.ts
- src/Typesense/StemmingDicitonary.ts
- src/Typesense/StemmingDictionaries.ts
- src/Typesense/StemmingDictionary.ts
- test/Typesense/StemmingDictionaries.spec.js
- test/Typesense/StemmingDictionary.spec.js
This PR implements support for the newest features for Typesense v28.0. The changes include dictionary-based stemming support, collection truncation, enhanced field configurations, and improved search parameters.
1. **Dictionary-based Stemming Support**:
- New `Stemming`, `StemmingDictionaries`, and `StemmingDictionary` classes
- Implementation of dictionary CRUD operations with `upsert` and `retrieve` methods
- Added stemming property to main client class
2. **Enhanced Search Parameters**:
- Added `max_filter_by_candidates` parameter to control fuzzy search behavior
- Introduced `rerank_hybrid_matches` parameter for multisearch
- Added `union` parameter to merge search results across collections
3. **Field and Collection Management**:
- Added `geopolygon` field type support
- Implemented …
> Incorporate v28 changes

- src/Typesense/Documents.ts
- test/Typesense/Documents.spec.js
Addresses #188 
This pull request introduces a new error handling mechanism in the `Documents` class within the `src/Typesense/Documents.ts` file. The main changes include the addition of a new error type and checks to ensure that provided documents are not empty.
Error handling improvements:
* [`src/Typesense/Documents.ts`](diffhunk://#diff-1e0565f0f17e3dfb64595df01f7506e4c30037e834ac03d758198f25e05c397eL4-R4): Added a new error type `RequestMalformed` to the import statement from `./Errors`.
* [`src/Typesense/Documents.ts`](diffhunk://#diff-1e0565f0f17e3dfb64595df01f7506e4c30037e834ac03d758198f25e05c397eR391-R393): Added a check to throw a `RequestMalformed` error if the provided documents array is empty.
* [`src/Typesense/Documents.ts`](diffhunk://#diff-1e0565f0f17e3dfb64595df01f7506e4c …
> fix(documents): throw on empty lists of documents

- src/Typesense/Collection.ts
The [`Pick<T,K>`](https://www.typescriptlang.org/docs/handbook/utility-types.html#picktype-keys) type doesn't infer if the keys are optional or not, leading to `token_separators` and `symbols_to_index` being required in the `Field` type.
> fix(collection): make `token_separators` & `symbols_to_index` partial

- src/Typesense/MultiSearch.ts
Improve TypeScript types for multi-search union responses and fix parameter normalization
- Currently, when using `union: true` in multi-search requests, the response type doesn't properly reflect the unified structure of the results
- This change adds proper type support for union responses and fixes a bug in parameter normalization
- Developers will now get correct TypeScript type inference when using union searches
1. **New Types in `MultiSearch.ts`**:
- `UnionSearchResponse<T>`: New type to handle unified search responses, extending base `SearchResponse` but replacing `request_params` with `union_request_params`
- `MultiSearchRequestsSchema<U>`: Made generic to support type inference based on union flag
1. **In `MultiSearch.ts`**:
- Modified `perform` method to support conditional …
> Add union response type support for multi-search requests

- src/Typesense/MultiSearch.ts
This type was made private in https://github.com/typesense/typesense-js/pull/266
> Make MultiSearchResponse public again

- src/Typesense/Collection.ts
- src/Typesense/Collections.ts
Addresses #269.
This pull request includes several changes to the `Typesense` module to improve type definitions and imports. The most important changes include modifying type imports in `Collection.ts` and exporting the `BaseCollectionCreateSchema` interface in `Collections.ts`.
Improvements to type definitions and imports:
* [`src/Typesense/Collection.ts`](diffhunk://#diff-6899637b797621e4136afa78180b0c9ea379fb9cdf50a521569fd6f33d85ec8dL2-R6): Modified imports to separately import `BaseCollectionCreateSchema` and `CollectionCreateSchema` from `Collections.ts`.
* [`src/Typesense/Collection.ts`](diffhunk://#diff-6899637b797621e4136afa78180b0c9ea379fb9cdf50a521569fd6f33d85ec8dL33-R37): Updated `CollectionFieldSchema` to use `BaseCollectionCreateSchema` instead of `CollectionCreateSchema` …
> fix(types): correct type reference in CollectionFieldSchema

- src/Typesense/Documents.ts
Add a `parent` optional key  in the `facet_count` response type, for when faceting by children fields and want to return their parent in full. Closes #275
> types: add `parent` key in the `facet_count` response

- package.json
- src/Typesense/Documents.ts
- src/Typesense/Keys.ts
- src/Typesense/MultiSearch.ts
- src/Typesense/Preset.ts
- src/Typesense/Presets.ts
- src/Typesense/SearchOnlyDocuments.ts
- src/Typesense/Types.ts
- src/Typesense/Utils.ts
- test/infix.type.test.ts
- tsconfig.test.json
Added compile-time validation for infix parameters and separate TypeScript config for tests.
1. **New Type Utilities in `Types.ts`**:
- `CommaSeparated<T, ToExtend>`: Validates comma-separated strings against allowed values at compile time
- `TrimString<S>`: Helper type for handling whitespace in string validation
2. **Type-Safe Infix Parameter in Search APIs**:
- Enhanced `SearchParams<TDoc, Infix>` with generic `Infix` parameter for compile-time validation
- Updated all search-related interfaces to support typed infix validation
3. **Separate Test Configuration**:
- `tsconfig.test.json`: Extends base config to include both source and test files
- `typecheck` script: Validates test files without emitting output
1. **In `Types.ts`**:
- Added `CommaSeparated` utility type that recursively …
> feat: add type-safe infix parameter validation & separate test TypeScript config

- src/Typesense/Types.ts
Add a default `string` param to avoid type errors when defining a var to be of type `SearchParams`
> chore(types): add default generic param for infix in search params

- lib/Typesense/SearchClient.d.ts
- src/Typesense/SearchClient.ts
Removed redundant typing for the `SearchClient.collections` function
> Remove redundant typing

- src/Typesense/MultiSearch.ts
- test/multisearch-abort.spec.ts
Add AbortSignal support to multisearch with test coverage
1. **In `src/Typesense/MultiSearch.ts`**:
- `AbortSignal` support through `SearchOptions` parameter in `perform()` method
- Pass abort signal to underlying API call for request cancellation
- Updated method signatures to use `SearchOptions` instead of cache-only options
1. **In `src/Typesense/MultiSearch.ts`**:
- **Import updates**: Added `SearchOptions` type import, converted to type-only imports
- **Method signature changes**: Updated `perform()` overloads to accept `SearchOptions`
- **Parameter handling**: Refactored options destructuring to use `SearchOptions`
- **API integration**: Added `abortSignal` parameter to `requestWithCache.perform()`
1. **New Test File `test/multisearch-abort.spec.ts`**:
- **Immediate rejection …
> feat(multisearch): Add AbortSignal Support to MultiSearch Operations

- lib/Typesense/Documents.d.ts
- src/Typesense/Documents.ts
This PR adds support for the optional `geo_distance_meters` field to the `SearchResponseHit<T>` type in the Typesense Node.js SDK.
`geo_distance_meters` is returned by the Typesense search API when a `sort_by=location(...)` clause is included in the search parameters. However, this field is currently missing from the TypeScript definition of `SearchResponseHit<T>`, leading to type errors or the need for manual casting.
- Added `geo_distance_meters?: number` to `SearchResponseHit<T>` interface in `Documents.ts`.
This change improves developer experience by:
- Providing accurate type information
- Preventing unnecessary `any` casts
- Enabling safe and clean usage of `geo_distance_meters` in strongly typed applications
> add `geo_distance_meters` to SearchResponseHit<T> type

- src/Typesense/Documents.ts
- updated `DeleteResponse` to be generic over document schema
- included typed `documents` field in response when `return_doc` is true
- updated `delete()` method to return `DeleteResponse<T>` for better typings
> feat(documents): extend type defs for document deletion

- src/Typesense/Documents.ts
- test/Typesense/Documents.spec.ts
- adds `throwOnFail` to `import` and `importStream` for better error control
- defaults `throwOnFail` to `true` to preserve existing failure behavior
- allows bypassing import errors by setting `throwOnFail: false`
- updates typings to propagate document schema type in import responses
- enhances test coverage for both `throwOnFail` enabled and disabled modes
- maintains backwards compatibility
> feat(documents): add `throwOnFail` option to import methods

- doc/examples/server/synonymSets.ts
- src/Typesense/Client.ts
- src/Typesense/Collection.ts
- src/Typesense/Collections.ts
- src/Typesense/SynonymSet.ts
- src/Typesense/SynonymSets.ts
- src/Typesense/Types.ts
- test/Typesense/AnalyticsEvents.spec.ts
- test/Typesense/AnalyticsRule.spec.ts
- test/Typesense/AnalyticsRules.spec.ts
- test/Typesense/Synonym.spec.ts
- test/Typesense/SynonymSet.spec.ts
- test/Typesense/SynonymSets.spec.ts
- test/Typesense/Synonyms.spec.ts
- test/utils.ts
Introduce Synonym Sets support in the Typesense client with full API integration, test coverage, and example usage.
1. **Client Support for Synonym Sets (`Client.ts`):**
- `synonymSets()` method added to the `Client` class with overloads for retrieving all sets or accessing individual sets by name.
- Internally maintains `_synonymSets` and `individualSynonymSets` for caching and reuse.
2. **Synonym Set Management Classes:**
- **`SynonymSet.ts`**: Defines `SynonymSet` class to handle upsert, retrieve, and delete operations for a specific synonym set.
- **`SynonymSets.ts`**: Manages operations for all synonym sets collectively.
3. **Collection Schema (`Collection.ts`, `Collections.ts`, `Types.ts`):**
- Collection creation and update schemas now support a `synonym_sets` array.
- …
> feat(synonyms): add support for V30 synonyms

- src/Typesense/ApiCall.ts
- src/Typesense/MultiSearch.ts
- test/Typesense/MultiSearch.spec.ts
- expose logger property in apicall and multisearch classes
- warn when individual search pagination parameters are used with union: true
- add helper method to detect pagination parameters in search objects
- add test for warning scenarios
> feat: add warning for individual pagination with union search

- src/Typesense/Documents.ts
Curated responses can include an arbitrary record of JSON values.
> feat(types): add potential `metadata` prop to search response type

- src/Typesense/Client.ts
- src/Typesense/CurationSet.ts
- src/Typesense/CurationSetItem.ts
- src/Typesense/CurationSetItems.ts
- src/Typesense/CurationSets.ts
- test/Typesense/AnalyticsRules.spec.ts
- test/Typesense/CurationSetItems.spec.ts
- test/Typesense/CurationSets.spec.ts
- test/Typesense/Override.spec.ts
- test/Typesense/Overrides.spec.ts
- Added: Curation Sets API (requires Typesense server v30+)
- New client entrypoints: `client.curationSets()` and `client.curationSets(name)`
- Endpoints supported:
- List all: `curationSets().retrieve()`
- Upsert: `curationSets(name).upsert({ items: [...] })`
- Retrieve: `curationSets(name).retrieve()`
- Delete: `curationSets(name).delete()`
- Items:
- List: `curationSets(name).items().retrieve()`
- Get: `curationSets(name).items(id).retrieve()`
- Upsert: `curationSets(name).items(id).upsert({...})`
- Delete: `curationSets(name).items(id).delete()`
- Notes:
- Tests are gated with a version check and run only on Typesense v30+.
- No breaking changes.
- Added: Synonym Set Items sub-API
- List items: `synonymSets(name).items().retrieve()`
- Get/Upsert/Delete single item: …
> add: curation_sets and analytics search event update
